# from https://github.com/testdrivenio/django-on-docker
# install with: docker-compose up -d --build

version: '3.7'

services:
  db:
    image: postgres:10.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  tripwatcher:
    build:
      context: ./
      dockerfile: ./tripwatcher/Dockerfile
    depends_on:
      - db
  web:
    build:
      context: ./
      dockerfile: ./reportcard/Dockerfile
    command: gunicorn reportcard:app -w 4 -b 0.0.0.0:8000
    volumes:
      - ./reportcard/:/usr/src/buswatcher/reportcard/
      - static_volume:/usr/src/buswatcher/reportcard/static
    expose:
      - 8000
    environment:
      - SECRET_KEY=please_change_me
      - SQL_DATABASE=buses
      - SQL_USER=buswatcher
      - SQL_PASSWORD=njtransit
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=buses
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - web
#  dns_updater:
#    build:
#      context: ./
#      dockerfile: ./dns_updater/Dockerfile

volumes:
  postgres_data:
  static_volume: