# mashup of https://github.com/sladkovm/docker-flask-gunicorn-nginx/
# and https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/

version: '3.7'

services:

  db:
    image: postgres:10.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  reportcard:
    container_name: reportcard
    restart: always
    build:
      context: ./
      dockerfile: ./reportcard/Dockerfile
    ports:
      - "8000:8000"
    command: gunicorn -w 4 -b :8000 reportcard:app
    environment:
      - SQL_DATABASE=exi
      - SQL_USER=buswatcher
      - SQL_PASSWORD=njtransit
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=buses
    depends_on:
      - db

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - reportcard

  tripwatcher:
    build:
      context: ./
      dockerfile: ./tripwatcher/Dockerfile
    depends_on:
      - db

  ddns:
    build: ./dns_updater/Dockerfile

volumes:
  postgres_data:

