# based on https://github.com/sladkovm/docker-flask-gunicorn-nginx/blob/master/docker-compose.yml

version: '3'

services:

  db:
    image: postgres:10.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  reportcard:
    container_name: reportcard
    restart: always
    build:
      context: ./
      dockerfile: ./reportcard/Dockerfile
    ports:
      - "8000:8000"
    command: gunicorn -w 4 -b :8000 reportcard:app
    environment:
      - SECRET_KEY=please_change_me
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
    depends_on:
      - db

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - reportcard

  tripwatcher:
    build:
      context: ./
      dockerfile: ./tripwatcher/Dockerfile
    command: python tripwatcher.py -s nj
    depends_on:
      - db
