version: '3.3'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'buses'
      MYSQL_USER: 'buswatcher'
      MYSQL_PASSWORD: 'njtransit'
      TZ: 'America/New_York'
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - database_volume:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  tripwatcher:
    build:
      context: ./
      dockerfile: ./tripwatcher/docker/Dockerfile.conda
    restart: always
#    volumes:
#      - buswatcher_config:/buswatcher/buswatcher/config
    depends_on:
      - db
  www:
    build:
      context: ./
      dockerfile: buswatcher/docker/Dockerfile.conda
    command: /opt/conda/envs/buswatcher/bin/gunicorn www:app -w 4 -b 0.0.0.0:8000
    restart: always
    volumes:
        - ./buswatcher/:/buswatcher
        - static_volume:/buswatcher/static
#        - buswatcher_config:/buswatcher/config
    expose:
      - 8000
    environment:
      - SQL_DB=buses
      - SQL_USER=buswatcher
      - SQL_PASSWORD=njtransit
      - SQL_HOST=db
      - SQL_PORT=3306 # - SQL_PORT=5432 # original
    depends_on:
      - db
  nginx:
    build:
      context: ./
      dockerfile: ./nginx/docker/Dockerfile
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - www
  generator:
    build:
      context: ./
      dockerfile: ./generator/docker/Dockerfile.conda
    restart: always
#    volumes:
#      - buswatcher_config:/buswatcher/buswatcher/config
    depends_on:
      - db
  dns_updater:
    restart: always
    build:
      context: ./
      dockerfile: ./dns_updater/docker/Dockerfile
volumes:
  database_volume:
  static_volume:
#  buswatcher_config:
