# install with: docker-compose up -d --build

#############################################################################
# nginx reverse proxy is handled manually outside the context of this stack
# dynamic DNS is handled manually outside the context of this stack

version: '3.7'

services:

  njbuswatcher_db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'buses'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'njtransit'
      TZ: 'America/New_York'
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - njbuswatcher_db_volume:/var/lib/mysql

  tripwatcher:
    build:
      context: ./
      dockerfile: ./docker/tripwatcher/Dockerfile
    restart: always
    volumes:
      - njbuswatcher_config_volume:/app/app/config
    depends_on:
      - njbuswatcher_db

  generator:
    build:
      context: ./
      dockerfile: ./docker/generator/Dockerfile
    restart: always
    volumes:
      - njbuswatcher_config_volume:/app/app/config
    depends_on:
      - njbuswatcher_db

  gunicorn:
    build:
      context: ./
      dockerfile: ./docker/gunicorn/Dockerfile
    # command: /opt/conda/envs/app/bin/gunicorn www:app -w 4 -b 0.0.0.0:8000
    restart: always
    volumes:
        # - ./app/:/app
        - njbuswatcher_static_volume:/app/app/static
        - njbuswatcher_config_volume:/app/app/config
    expose:
       - 8082
    environment:
      - SQL_DB=buses
      - SQL_USER=app
      - SQL_PASSWORD=njtransit
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - njbuswatcher_db


volumes:
  njbuswatcher_db_volume:
  njbuswatcher_static_volume:
  njbuswatcher_config_volume:
