# after https://github.com/ericcgu/Flask-Gunicorn-Nginx-Postgres-Docker

version: '3.7'

services:
  postgres:
    build:
      context: ./
      dockerfile: ./postgres/Dockerfile
    restart: always
    volumes:
      - ./db:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'master'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'temp'

  gunicorn:
    restart: always
    build:
      context: ./
      dockerfile: ./gunicorn/Dockerfile
    environment:
      ENV: "Development"
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      OAUTHLIB_INSECURE_TRANSPORT: 1
      OAUTHLIB_RELAX_TOKEN_SCOPE: 1
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - .:/usr/src/app/static
    env_file: .env
    command: gunicorn -w 2 -b :8000 itemcatalog:app

  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    restart: always
    volumes:
      - /www/static
    ports:
      - "80:80"
    depends_on:
      - gunicorn

  tripwatcher:
    build:
      context: ./
      dockerfile: ./tripwatcher/Dockerfile
    depends_on:
      - postgres

  ddns:
    build:
      context: ./
      dockerfile: ./dns_updater/Dockerfile