# from https://github.com/testdrivenio/django-on-docker
# mysql from https://medium.com/@chrischuck35/how-to-create-a-mysql-instance-with-docker-compose-1598f3cc1bee
# install with: docker-compose up -d --build

version: '3.3'

services:  
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'buses'
      MYSQL_USER: 'buswatcher'
      MYSQL_PASSWORD: 'njtransit'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  tripwatcher:
    build:
      context: ./
      dockerfile: ./tripwatcher/docker/Dockerfile.conda
    depends_on:
      - db
  flask_gunicorn:
    build:
      context: ./
      dockerfile: ./reportcard/docker/Dockerfile.conda
    command: /opt/conda/envs/buswatcher/bin/gunicorn reportcard:app -w 4 -b 0.0.0.0:8000
    volumes:
      - ./reportcard/:/reportcard/
      - static_volume:/reportcard/static
    expose:
      - 8000
    environment:
      - SQL_DB=buses
      - SQL_USER=buswatcher
      - SQL_PASSWORD=njtransit
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db
  nginx:
    build:
      context: ./
      dockerfile: ./nginx/docker/Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - flask_gunicorn
  dns_updater:
    build:
      context: ./
      dockerfile: ./dns_updater/docker/Dockerfile

volumes:
  my-db:
  static_volume: