name: buswatcher
channels:
  - conda-forge
  - defaults
dependencies:
  - apscheduler
  - flask
  - flask-assets
  - flask-cors
  - geojson
  - geopandas
  - gunicorn
  - jinja2
  - numpy
  - pandas # future for some reason, this doesn't actually get installed on OSX and needs to be isntalled manually after the build
  - pip
  - pymysql
  - pyquery
  - python=3.7.3
  - python-dateutil
  - pytz
  - scipy
  - shapely
  - sqlite
  - werkzeug
  - pip:
    - fiona==1.8.4
    - flask-bootstrap4
    - sqlalchemy
    - locustio


