# this is where the routes are configured for the homepage, and the dashboard
# 5 and only 5, 6th is TBD


reportcard_routes=[ \
    {'route':'84', 'grade':'A', 'description':'Through-running DINGO from Journal Square to Union City along Palisade Ave every 15-20 minutes throughout the day.','description_long':'Morbi ac mi eu enim tempus aliquam nec et mi. Etiam in odio quis nunc aliquet ultricies. Nullam tristique velit volutpat, laoreet ipsum quis, ultricies dui. Nunc mattis est nec leo sodales, et vestibulum lorem sodales lorem sodales. Morbi ac mi eu enim tempus aliquam nec et mi. Etiam in odio quis nunc aliquet ultricies. Nullam tristique velit volutpat, laoreet ipsum quis, ultricies dui. Nunc mattis est nec leo sodales, et vestibulum lorem sodales lorem sodales.','schedule_url':'https://www.njtransit.com/pdf/bus/T0084.pdf'},
    {'route':'86', 'grade':'B', 'description':'Our community\'s bus connection to downtown Jersey City\'s Grove Street area and the Newport Center Mall.','description_long':'Morbi ac mi eu enim tempus aliquam nec et mi. Etiam in odio quis nunc aliquet ultricies. Nullam tristique velit volutpat, laoreet ipsum quis, ultricies dui. Nunc mattis est nec leo sodales, et vestibulum lorem sodales lorem sodales. Morbi ac mi eu enim tempus aliquam nec et mi. Etiam in odio quis nunc aliquet ultricies. Nullam tristique velit volutpat, laoreet ipsum quis, ultricies dui. Nunc mattis est nec leo sodales, et vestibulum lorem sodales lorem sodales.','schedule_url':'https://www.njtransit.com/pdf/bus/T0086.pdf'},
    {'route':'87', 'grade':'C', 'description':'The Heights\' main bus backbone, providing its most frequent links to rail transit at Journal Square and Hoboken Terminal.','description_long':'Morbi ac mi eu enim tempus aliquam nec et mi. Etiam in odio quis nunc aliquet ultricies. Nullam tristique velit volutpat, laoreet ipsum quis, ultricies dui. Nunc mattis est nec leo sodales, et vestibulum lorem sodales lorem sodales. Morbi ac mi eu enim tempus aliquam nec et mi. Etiam in odio quis nunc aliquet ultricies. Nullam tristique velit volutpat, laoreet ipsum quis, ultricies dui. Nunc mattis est nec leo sodales, et vestibulum lorem sodales lorem sodales.','schedule_url':'https://www.njtransit.com/pdf/bus/T0087.pdf'},
    {'route':'119', 'grade':'C', 'description':'Our Central Avenue local and main express commuter line to midtown Manhattan.','description_long':'The 119 provides a lifeline to Hudson County but is too long. There was a big campaign to extend service but it still has not worked. What we think is this and you can see the problems here and here. Click on this below to see.','schedule_url':'https://www.njtransit.com/pdf/bus/T0119.pdf'},
    {'route':'123', 'grade':'A', 'description':'Alternate Palisade Ave local service to Union City and Manhattan.','description_long':'Morbi ac mi eu enim tempus aliquam nec et mi. Etiam in odio quis nunc aliquet ultricies. Nullam tristique velit volutpat, laoreet ipsum quis, ultricies dui. Nunc mattis est nec leo sodales, et vestibulum lorem sodales lorem sodales. Morbi ac mi eu enim tempus aliquam nec et mi. Etiam in odio quis nunc aliquet ultricies. Nullam tristique velit volutpat, laoreet ipsum quis, ultricies dui. Nunc mattis est nec leo sodales, et vestibulum lorem sodales lorem sodales.','schedule_url':'https://www.njtransit.com/pdf/bus/T0123.pdf'}\
    ]

grade_descriptions=[ \
    {'grade':'A', 'description':'Exceptional. Always on time and with a smile.'},
    {'grade':'B', 'description':'Good and could be better.'},
    {'grade':'C', 'description':'The average bear. Service is neither too hot nor too cold.'},
    {'grade':'D', 'description':'A dingo ate your baby and no one cried.'},
    {'grade':'F', 'description':'Oh my god you are the worst.'}\
    ]