# this is where the routes are configured for the homepage, and the dashboard
# 5 and only 5, 6th is TBD


reportcard_routes=[ \
    {'route':'84', 'grade':'A', 'description':'Through-running DINGO from Journal Square to Union City along Palisade Ave every 15-20 minutes throughout the day.','description_long':'Morbi ac mi eu enim tempus aliquam nec et mi. Etiam in odio quis nunc aliquet ultricies. Nullam tristique velit volutpat, laoreet ipsum quis, ultricies dui. Nunc mattis est nec leo sodales, et vestibulum lorem sodales lorem sodales. Morbi ac mi eu enim tempus aliquam nec et mi. Etiam in odio quis nunc aliquet ultricies. Nullam tristique velit volutpat, laoreet ipsum quis, ultricies dui. Nunc mattis est nec leo sodales, et vestibulum lorem sodales lorem sodales.','schedule_url':'https://www.njtransit.com/pdf/bus/T0084.pdf'},
    {'route':'86', 'grade':'B', 'description':'Our community\'s bus connection to downtown Jersey City\'s Grove Street area and the Newport Center Mall.','description_long':'Morbi ac mi eu enim tempus aliquam nec et mi. Etiam in odio quis nunc aliquet ultricies. Nullam tristique velit volutpat, laoreet ipsum quis, ultricies dui. Nunc mattis est nec leo sodales, et vestibulum lorem sodales lorem sodales. Morbi ac mi eu enim tempus aliquam nec et mi. Etiam in odio quis nunc aliquet ultricies. Nullam tristique velit volutpat, laoreet ipsum quis, ultricies dui. Nunc mattis est nec leo sodales, et vestibulum lorem sodales lorem sodales.','schedule_url':'https://www.njtransit.com/pdf/bus/T0086.pdf'},
    {'route':'87', 'grade':'C', 'description':'The Heights\' main bus backbone, providing its most frequent links to rail transit at Journal Square and Hoboken Terminal.','description_long':'The 87 snakes through The Heights, linking to important rail stations at Journal Square, the 9th Street Light Rail Station, and Hoboken Terminal. It has the worst bunching problems of all NJTransit routes in the area due to heavy traffic, railroad grade crossings, and more.' ,'schedule_url':'https://www.njtransit.com/pdf/bus/T0087.pdf'},
    {'route':'119', 'grade':'C', 'description':'Our Central Avenue local and main express commuter line to midtown Manhattan.','description_long':'The 119 provides a lifeline to Hudson County but is too long, infrequent, and overcrowded.','schedule_url':'https://www.njtransit.com/pdf/bus/T0119.pdf'},
    {'route':'123', 'grade':'A', 'description':'Alternate Palisade Ave local service to Union City and Manhattan.','description_long':'Morbi ac mi eu enim tempus aliquam nec et mi. Etiam in odio quis nunc aliquet ultricies. Nullam tristique velit volutpat, laoreet ipsum quis, ultricies dui. Nunc mattis est nec leo sodales, et vestibulum lorem sodales lorem sodales. Morbi ac mi eu enim tempus aliquam nec et mi. Etiam in odio quis nunc aliquet ultricies. Nullam tristique velit volutpat, laoreet ipsum quis, ultricies dui. Nunc mattis est nec leo sodales, et vestibulum lorem sodales lorem sodales.','schedule_url':'https://www.njtransit.com/pdf/bus/T0123.pdf'}\
    ]

grade_descriptions=[ \
    {'grade':'A', 'description':'Service is provided in line with rider expectations of reliability, capacity, and quality.'},
    {'grade':'B', 'description':'Service is usually good but occaissionaly falls short of rider expectations.'},
    {'grade':'C', 'description':'Service meets the needs of riders some of the time, but suffers from serious shortcomings and gaps. Focused action is required to improve service in the near-term.'},
    {'grade':'D', 'description':'Service only rarely meet the needs of riders, and is in danger of failing.'},
    {'grade':'F', 'description':'Service frequently fails to meeting rider needs and expectations. Immediate action required to achieve minimum level of service.'}\
    ]